Using == for equality sign in python

In [5]:
y = 2**3 # = for assignment
y

8

In [9]:
y ==12 # == for equality


False

In [10]:
y ==8 

True

Reassiged values

In [11]:
z = 2
z

2

In [12]:
z = 4
z

4

In [13]:
z + 5

9

Comment

In [14]:
# This is not code
# z + 5
# z

Line continuation

In [20]:
1 + 3 * \
4

13

Indexing: Python starts indexing from 0, 1, 2, 3, 4 ...

In [21]:
'Monday'[2]

'n'

In [22]:
'Monday'[0]

'M'

Indentation

In [31]:
def five(x):
    x = 5
    return x

print(five(3))

5


In [26]:
x = add(1,2)

In [27]:
x

[]

In [61]:
new_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 10]
new_list.index(5)

4

In [62]:
new_list.count(5)

2

In [63]:
new_list.append(11)
new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 10, 11]

In [64]:
new_list.extend([12, 13])

In [65]:
new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 10, 11, 12, 13]

In [66]:
del(new_list[:3])

In [67]:
new_list

[4, 5, 6, 7, 8, 9, 5, 10, 11, 12, 13]

In [68]:
new_list.pop(-1)
new_list

[4, 5, 6, 7, 8, 9, 5, 10, 11, 12]

In [69]:
new_list.sort()

In [70]:
new_list

[4, 5, 5, 6, 7, 8, 9, 10, 11, 12]

In [71]:
new_list.insert(1, 6)

In [72]:
new_list

[4, 6, 5, 5, 6, 7, 8, 9, 10, 11, 12]

In [73]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [74]:
import numpy as np

In [75]:
new_list

[4, 6, 5, 5, 6, 7, 8, 9, 10, 11, 12]

In [76]:
new_list_array = np.array(new_list)
new_list_array

array([ 4,  6,  5,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
my_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
my_array.shape

(2, 4)

In [79]:
new_list_array.shape

(11,)

In [87]:
my_array[0,:]

array([1, 2, 3, 4])

In [91]:
my_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
np.mean(my_array)

4.5

In [93]:
np.median(my_array)

4.5

In [100]:
my_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
np.matmul(my_array, [1, 2, 3, 4])

array([30, 70])

In [102]:
np.corrcoef(my_array)

array([[1., 1.],
       [1., 1.]])

In [104]:
practise_array = np.array([[2, 4, 6, 8], [9, 3, 8, 7], [2, 5, 9, 8], [1, 6, 2, 3]])
practise_array

array([[2, 4, 6, 8],
       [9, 3, 8, 7],
       [2, 5, 9, 8],
       [1, 6, 2, 3]])

In [105]:
practise_array[1:3, 2]

array([8, 9])

In [107]:
practise_array[2:, 1:3]

array([[5, 9],
       [6, 2]])